trip form: add callback for detecting when all submodes are disabled
ibi-group/otp-ui pull request #28
Opened 2024-09-09 20:54 UTC by daniel-heppner-ibigroup

This PR adds a callback to detect when all the submodes under a mode button have been disabled. This will allow us to disable the mode button when all its submodes have been turned off.

2024-09-12 21:07 UTC, amy-corson-ibigroup reviewed
Just to clarify, when I run this branch in otp-rr, if I disable all submodes, this `handleSettingChange` resets all submodes back to `checked`. Is that the default behavior we want even if there is no `onAllSubmodesDisabled` prop?

2024-09-13 17:20 UTC, josh-willis-arcadis commented
@amy-corson-ibigroup Nope. Good catch! I will fix this.

2024-09-13 17:40 UTC, daniel-heppner-ibigroup commented
> Just to clarify, when I run this branch in otp-rr, if I disable all submodes, this `handleSettingChange` resets all submodes back to `checked`. Is that the default behavior we want even if there is no `onAllSubmodesDisabled` prop?

I think this is happening when the prop is enabled because it's deleting the submodes which causes the defaults to be selected. It's unavoidable in that case but should only be happening then. (I see Josh fixed it though!)

2024-09-18 17:19 UTC, amy-corson-ibigroup approved these changes
Looking good! Thanks for the changes

2024-09-23 19:49 UTC, binh-dam-ibigroup requested changes
Can you add a Storybook action so we can see the new `onAllSubmodesDisabled` callback being fired. See the other comments too.

2024-09-23 19:49 UTC, binh-dam-ibigroup commented on packages/trip-form/src/MetroModeSelector/SubSettingsPane.tsx
> +      // check if setting is a transport mode setting
Move this comment to just before line 194.

2024-09-23 19:49 UTC, binh-dam-ibigroup commented on packages/trip-form/src/MetroModeSelector/SubSettingsPane.tsx
> +      // check if setting is a transport mode setting
You can probably move this variable outside of the `useCallback` block, e.g. move to line 191.

2024-09-23 19:49 UTC, binh-dam-ibigroup commented on packages/trip-form/src/MetroModeSelector/AdvancedModeSettingsButton.story.tsx
In this file, can you please bind the new `onAllSubmodesDisabled` prop to a new Storybook `action`, so we can see the event being fired with the corresponding parameters?

2024-09-24 17:11 UTC, josh-willis-arcadis commented on packages/trip-form/src/MetroModeSelector/mockButtons.tsx
This was renamed because the build on the new version of storybook was failing. When .story is in the filename, a story is expected and there is no story in this file. These mocks are not used anywhere else besides storybook.

2024-09-24 19:00 UTC, binh-dam-ibigroup commented on packages/trip-form/src/MetroModeSelector/mockButtons.tsx
I just realized there is a `__mocks__` folder for this package, could you move `mockButtons.tsx` into that folder?

2024-09-24 20:39 UTC, binh-dam-ibigroup commented on packages/trip-form/src/MetroModeSelector/AdvancedModeSettingsButton.story.tsx
> +    onAllSubmodesDisabled: { action: "all submodes disabled" }
I don't see "all submodes disabled" appearing in the Storybook action pane, did I miss something?

2024-09-24 20:46 UTC, binh-dam-ibigroup commented on packages/trip-form/src/MetroModeSelector/AdvancedModeSettingsButton.story.tsx
> +    onAllSubmodesDisabled: { action: "all submodes disabled" }
> I don't see "all submodes disabled" appearing in the Storybook action pane, did I miss something?

I pulled a previous commit, sorry, ignore that comment.

2024-09-24 20:46 UTC, binh-dam-ibigroup approved these changes
I think this is good to go!

2024-09-25 19:40 UTC, merged